title: Diana Rocío Galindo # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: Full data stack <br><br> <a href="https://www.linkedin.com/in/drgalindog/">LinkedIn</a>
 <br> 
 <br> 
 <br>
theme: jekyll-theme-minimal
