title: Diana Rocío Galindo # your name (or website title) here
logo: "/images/202501.png?raw=true" # your photo (or logo) here
description: Full data stack | Data science | Geospatial
theme: jekyll-theme-minimal
